import Head from 'next/head'
import HomePage from "@/component/home";

const Home = () => {
  // const [code, setCode] = useState("")
  // const [monacoCtx, setMonacoCtx] = useState(null)
  // const [errors, setErrors] = useState([])

  return (
    <>
      <Head>
        <title>Cyclone Specification Language</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </>
  )
}

export default Home